services:

  db:
    image: postgres
    restart: always # restart policy TODO check
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: verysecretpassword
      POSTGRES_USER: dbadmin
    ports:
      - "5432:5432"
    networks:
      - mini_docker_network
      
  miniserver:
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - mini_docker_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ChatContext=Host=db;Username=dbadmin;Password=verysecretpassword

networks:
  mini_docker_network:
    driver: bridge