services:

  db:
    image: postgres
    restart: always # restart policy TODO check
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: verysecretpassword
      POSTGRES_USER: dbadmin
    ports:
      - "5432:5432"