name: Build and deploy ASP.Net Core app to Azure Web App - nssminichat

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Ensure working directory
        run: |
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "Listing contents:"
          Get-ChildItem
        shell: pwsh
        working-directory: ./MiniServer

      - name: Build with dotnet
        working-directory: ./MiniServer
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./MiniServer
        run: |
          if (Test-Path "${{env.DOTNET_ROOT}}") {
            Write-Host "Publishing to ${{env.DOTNET_ROOT}}/myapp"
            dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
          } else {
            Write-Host "DOTNET_ROOT is not set or directory doesn't exist"
            exit 1
          }
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/myapp"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'main'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nssminichat'
          slot-name: 'main'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_68F2C670FF30473096A5C6FEEFBE3021 }}
